### ISSUE TITLE
How can I close the window while exit the program too.

### ISSUE THREAD

**Issue by tangliming** [raintean/blink#1]
Hi, I am using the example in the project man page, but there is a problem, if you use 
`<-make(chan bool)`
to let the program keep runing, then after you close the web window, the program won't exit. 

How can I make the program exit entirely after I close the last window?

**Comment by raintean** [comment]
这里的channel仅仅起阻塞程序退出的作用,如果程序只有一个主窗口,可以使用如下方法
```golang
package main

import (
	"blink-demo/ui/bin"
	"github.com/elazarl/go-bindata-assetfs"
	"github.com/raintean/blink"
	"log"
)

func main() {
	//退出信号
	exit := make(chan bool)

	//启用调试模式
	blink.SetDebugMode(true)

	//初始化blink
	err := blink.InitBlink()
	if err != nil {
		log.Fatal(err)
	}

	//挂载嵌入资源到虚拟文件系统
	blink.RegisterFileSystem("app", &assetfs.AssetFS{
		Asset:     ui.Asset,
		AssetDir:  ui.AssetDir,
		AssetInfo: ui.AssetInfo,
	})

	//创建一个新的窗口
	view := blink.NewWebView(false, 1366, 920)
	view.LoadURL("http://app/index.html")
	view.SetWindowTitle("Blink Demo")
	view.MoveToCenter()
	view.ShowWindow()
	view.On("destroy", func(_ *blink.WebView) {
		close(exit)
	})

	//等待退出
	<-exit
}
```
监听窗口的destroy事件,然后close channel.  
如果你的程序是多窗口设计,就需要你自己去实现对应的close逻辑了.  
  
当然咯,我这里只是用了channel来做阻塞,你完全可以使用其他的方式来阻塞main thread的退出,如waitGroup等.  
  
另外,我写了一个新的demo项目,不过还在进行中

**Comment by tangliming** [comment]
It works perfectly, thanks a lot.
