### ISSUE TITLE
一台机多个应用执行报错

### ISSUE THREAD

**Issue by ghost** [raintean/blink#10]

**Comment by ghost** [comment]
拖动按钮没有鼠标事件，和库无关

**Comment by raintean** [comment]
两个问题请开两个issue,  针对这两个问题都回答一下, 一台机器多个应用同时执行的问题其实很简单, 因为dll会默认释放到一个目录,所以有冲突.  等下加上自定义目录的功能. 第二个, 是因为我使用的dll比较旧, 内嵌的dll还是有拖动事件bug的  等我更新

**Comment by zhuwei** [comment]
怪事，我的exe拿到一台新的xp上运行，显示窗体后，过几秒会闪退，没捕获到log，再启动就没任何问题。
