### ISSUE TITLE
有的时候会提示注册的JS函数没有定义

### ISSUE THREAD

**Issue by tangliming** [raintean/blink#16]
注册了BlinkFunc.GetConfig函数，但是有的时候运行程序起来之后，透过网页的js去调用这个函数，在devtool里会看到下面的提示：
unhandled promise rejection TypeError: BlinkFunc.GetConfig is not a function

重新运行程序又好了。但是不定时的会出来。

**Comment by raintean** [comment]
函数的注入view.Inject,必须在网页加载之前. 你这里的webview的加载是异步的吗? 方便的话,贴一下代码.

**Comment by tangliming** [comment]
这个不是一直会发生，而是有时候。

blink.SetDebugMode(false)
	//初始化blink模块
	err := blink.InitBlink()
	if err != nil {
		log.Fatal(err)
	}
	blink.RegisterFileSystem("app", &assetfs.AssetFS{
		Asset:     Asset,
		AssetDir:  AssetDir,
		AssetInfo: AssetInfo,
	})
	time.Sleep(time.Duration(20) * time.Millisecond)
	//新建view,加载URL
	view = blink.NewWebView(false, 1060, 800)
	//直接加载虚拟文件系统中的网页
	view.LoadURL("http://app/index.html")
	view.MoveToCenter()
	view.ShowWindow()

上面增加那个sleep是我发现有时候程序还会crash，我感觉是blink.InitBlink没有做完，但是虽然加了，还是偶尔启动程序就会crash

**Comment by tangliming** [comment]
> 函数的注入view.Inject,必须在网页加载之前. 你这里的webview的加载是异步的吗? 方便的话,贴一下代码.

应该是这个问题了，我是在	view.ShowWindow() 之后才view.Inject的，我先修改测试看看，如果没有问题就过来关闭该issue，感谢

**Comment by raintean** [comment]
这个地方我打算更改一下,Inject做成和初始化脱钩的,实时起作用. 感觉大家在这个地方出的问题比较多.

**Comment by tangliming** [comment]
测试了一下午，没有出现这个问题，关闭该issue，谢谢
