### ISSUE TITLE
bin是哪里的 我是新手

### ISSUE THREAD

**Issue by kxg3030** [raintean/blink#18]
![image](https://user-images.githubusercontent.com/48542529/57519440-d3869780-734d-11e9-890c-c083121b8bf5.png)

**Comment by raintean** [comment]
go-bindata生成的,符合http.FileSystem接口即可,也可以直接http.Dir用磁盘上的文件夹

**Comment by tangliming** [comment]
比如你有一个文件夹test,里面有index.html, test.html，进入test文件夹执行命令：
```
go-bindata ./...
```
完成以后就会生成一个bindata.go，把这个文件拷贝到你的项目目录里编译就好了。

**Comment by kxg3030** [comment]
请问 调试模式怎么使用呢

**Comment by kxg3030** [comment]
webview关闭的时候 怎么关闭后台的程序呢 有事件监听么

**Comment by raintean** [comment]
@kxg3030  你问的这两个问题   readme和issue里面都有

**Comment by raintean** [comment]
长时间没有回应, 关闭该issue
