### ISSUE TITLE
请问没有看见node.dll？

### ISSUE THREAD

**Issue by zhuwei** [raintean/blink#2]
您自己通过源码编译成blink.dll？是基于mb免费的？
如果想用收费的，应该怎么弄？

**Comment by raintean** [comment]
免费版本的dll是从官方下载的,然后以二进制的方式嵌入到程序中的.   
该库只针对免费版本的dll,听说收费版本的dll在API上有了变更,所以应该是不兼容的.  
另外在后续的版本中,该库将提供自己替换嵌入dll的功能.

**Comment by zhuwei** [comment]
@raintean 感谢您的回复。期待后续版本！
