### ISSUE TITLE
请问如何生成blink64.dll?

### ISSUE THREAD

**Issue by bracez** [raintean/blink#20]
如果没有弄错，Miniblink应该只有node.dll 32位版本的，
请问您是如何生成blink64.dll的呢？难道有64位的node.dll，还是自己编译的？
谢谢

**Comment by raintean** [comment]
64bit的dll是官方群里面下载的, 官方关于64的发布没有放在网站上. 而是放群里. 自己编译是不可能的, 尝试过, 一来是机器性能不足, 二来是mb的项目配置好像没有完全分离本地环境. 经常编译不通过. 尝试无果还是放弃了自己编译.

**Comment by bracez** [comment]
非常感谢您的回答，还是用官方发布的32版本了。
