### ISSUE TITLE
请教，如何正确设置 http request header?

### ISSUE THREAD

**Issue by bracez** [raintean/blink#21]
用chrome的浏览器测试get或者post 数据到后台API都没有问题。
但是用您这个GUI封装以后，发现post的数据头格式不对，我想应该可以在程序里面设置request header吧?例如content-type 或  access-control-request-headers之类的.

**Comment by bracez** [comment]
补充：用miniblink提供的工具测试，也没有问题。问题之是在用这个go封装以后产生的。

**Comment by raintean** [comment]
能否详细说明下, 究竟怎么不对？

**Comment by bracez** [comment]
请看Request Headers, 代码都是完全一样的，没有任何区别，但是用chrome或者miniblink测试工具，或者您这个封装，Headers都不一样。
具体Header请查阅下面的截图连接，谢谢
https://imgur.com/a/dICArw1

**Comment by raintean** [comment]
这个是因为blink对所有的请求做了URL拦截(以实现虚拟网络文件系统), 所以你的ajax请求也会被拦截, 但是最终放行, 这个过程中可能会造成请求被修改.

具体请查看 netfs.c 中的 handleLoadUrlBegin 方法

**Comment by bracez** [comment]
谢谢，看不太明白handleLoadUrlBegin的方法。不过，还是非常感谢您的解释。
