### ISSUE TITLE
增加托盘，增加菜单，增加无边框

### ISSUE THREAD

**Issue by bishen** [raintean/blink#25]
增加托盘，增加菜单，增加无边框，完美

**Comment by raintean** [comment]
托盘不属于这个库需要实现的范围. 你可以使用cgo自己写, 或者搞一个golang的托盘图标库. 比如 lantern的有一个还挺好用. 菜单同样也是, 或者你可以在html中实现菜单, 均可. 无边框本来就支持, New的时候第一个参数传入true即可.
