### ISSUE TITLE
在html文件中是否可以直接载入go的注入值

### ISSUE THREAD

**Issue by zhuwei** [raintean/blink#4]
可以通过js的ready赋值
但这有延迟，不合适

**Comment by raintean** [comment]
如果html中需要直接获取到go注入的值的话, 我目前只能想到的方式是  *模板占位*  的方式  
类似这样的形式:
```html
<h1> ${BlinkData.title} </h1>
```
但是这种方式我并不是很认同, 怕和某些js模板语言起冲突.  
不知你有什么更好的设计?

**Comment by zhuwei** [comment]
原本想用vue.js来解决这个问题，我试了下跟在document.ready没什么区别。
我用mb他们的测试wkexe.exe和fast-mb.exe，vue.js效果很好。这个是为什么呢？
如果初始加载很快，这个我想不需要注入。注入确实有些麻烦。因为到后面又要加if和for，否则仅仅是值注入，感觉满足不了。if和for又更麻烦一点。
至于占位方式，我个人觉得可以自由设置，类似php的一些框架

**Comment by zhuwei** [comment]
关于速度问题，会不会dll不是最新？

**Comment by raintean** [comment]
你说的速度的问题,是指document ready事件出来得慢吗?

**Comment by zhuwei** [comment]
@raintean 嗯，是的，要等几秒(3秒左右)

**Comment by raintean** [comment]
好的,  我测试一下 看看是什么问题造成的

**Comment by zhuwei** [comment]
非常感谢！

**Comment by raintean** [comment]
我这边测试了一下,并没有出现你说的问题.
这是测试代码:
<img width="1349" alt="code" src="https://user-images.githubusercontent.com/7589835/50752173-13e2e580-1288-11e9-9822-77e15f76842e.png">
这是测试结果:
<img width="765" alt="result" src="https://user-images.githubusercontent.com/7589835/50752181-1c3b2080-1288-11e9-82e6-89ee06d4898b.png">
你看一下,你是不是这样的情况.  或者贴一下你的代码.

**Comment by zhuwei** [comment]
按照你测试的方式，我这边也和你一样。
但实际变更的效果不一样，我看能不能拍个视频

**Comment by zhuwei** [comment]
视频上传不了。这样的测试结果来看，就不是ready执行慢，而且渲染画面结束慢？
```
console.log(new Date(), "init");
$(document).ready(function(){
	console.log(new Date(), "ready");
	$('#span-title').text(BlinkData.title);
});
```
你试试这个，你发现span-title的值等一会儿才能出现

**Comment by zhuwei** [comment]
还是不行的话，我这边把资源打个包给你，你留个邮箱？

**Comment by raintean** [comment]
你开个git  repo就OK了

**Comment by raintean** [comment]
你的代码我这里也测试了, 也没有任何问题.  你的jQuery是不是网络引用?

**Comment by zhuwei** [comment]
github.com/zhuwei/blink-demo

**Comment by zhuwei** [comment]
资源都不是网络应用，都是本地

**Comment by zhuwei** [comment]
html直接获取go的注入值，如果能实现go的template解析就好了。就用现成的。。。还有range

**Comment by raintean** [comment]
你这个要求  完全可以自己实现  http.FileSystem 来达到, 目前有一个好的想法, 但是不知道什么时候有时间来实现.

**Comment by zhuwei** [comment]
明白了，谢谢。我研究下
