### ISSUE TITLE
透过view.Inject注入的函数有很高的几率不会执行

### ISSUE THREAD

**Issue by tlmcasper** [raintean/blink#5]
在网页上调用
BlinkFunc.MostTop(flag)
或者调用透过view.inject注入的函数

然后点击网页触发函数，native function有大概率不会执行，10次里面大概只有4次成功。

**Comment by raintean** [comment]
~~请详述你的问题, MostTop和调用的关系?  还是 MostTop调用不成功 / inject调用也不成功 两个问题?~~  
  
刚刚我测试过了,并没有发现问题,建议你先触发一个网页内的方法,console.log一下,然后再调用BlinkFunc的方法,以便于区分是否是点击事件没有触发还是native function没有被调用.

**Comment by raintean** [comment]
已经修复, 该issue关闭
