### ISSUE TITLE
是否考虑增加一个设置左上角图标的函数？

### ISSUE THREAD

**Issue by zhuwei** [raintean/blink#9]
另外想问下，exe的图片有没有好的办法修改。通过rice貌似win32系统不行

**Comment by raintean** [comment]
api我会加一下, 关于你另外问的一个问题, 属于golang的范畴. 我自己用的goversioninfo, 32/64位都OK. 几乎完美.

**Comment by zhuwei** [comment]
非常感谢，一直没找到过类似goversioninfo的东西

**Comment by raintean** [comment]
api已经加好了, 不过还在测试中, 等我测试稳定了.

**Comment by zhuwei** [comment]
额，我fork出去加了个。等你上传我看看。。

**Comment by raintean** [comment]
牛批  兄弟

**Comment by zhuwei** [comment]
汗，我还加了个另存文件选择框，还没上传

**Comment by raintean** [comment]
已经完成, #12
